# Artificial Neural Network

### Importing the libraries

In [134]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [135]:
tf.__version__

'2.18.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [136]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values # write down here why we are using 3:-1 why these columns
y = dataset.iloc[:, -1].values

We used dataset.iloc[ : , 3 : -1 ] to select the columns from 3rd index upto the last except the last column as the last column consist of the y value and the first three columns bing name creditScore and index are not needed to train the model

In [137]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [138]:
# from google.colab import drive
# drive.mount('/content/drive')

In [139]:
print(X[:5])

[[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 'Female' 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 'Female' 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 'Female' 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 'Female' 43 2 125510.82 1 1 1 79084.1]]


In [140]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [141]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

X[:, 2] = X[:, 2].astype(str)
X[:, 2] = le.fit_transform(X[:, 2])

In [142]:
print(X[:8])

[[619 'France' 0 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 0 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 0 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 0 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 0 43 2 125510.82 1 1 1 79084.1]
 [645 'Spain' 1 44 8 113755.78 2 1 0 149756.71]
 [822 'France' 1 50 7 0.0 2 1 1 10062.8]
 [376 'Germany' 0 29 4 115046.74 4 1 0 119346.88]]


One Hot Encoding the "Geography" column

In [143]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X=ct.fit_transform(X)

In [144]:
print(X[:5])

[[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]
 [0.0 0.0 1.0 608 0 41 1 83807.86 1 0 1 112542.58]
 [1.0 0.0 0.0 502 0 42 8 159660.8 3 1 0 113931.57]
 [1.0 0.0 0.0 699 0 39 1 0.0 2 0 0 93826.63]
 [0.0 0.0 1.0 850 0 43 2 125510.82 1 1 1 79084.1]]


### Splitting the dataset into the Training set and Test set

In [145]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [146]:
X_train.shape , y_train.shape , X_test.shape , y_test.shape

((8000, 12), (8000,), (2000, 12), (2000,))

### Feature Scaling

In [147]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [148]:
ann = tf.keras.models.Sequential([
    tf.keras.Input(shape=(12,)),
    tf.keras.layers.Dense(units=6, activation='relu'),
    tf.keras.layers.Dense(units=6, activation='relu'),
    tf.keras.layers.Dense(units=3, activation="relu"),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
]
)

### Adding the input layer and the first hidden layer

### Adding the second hidden layer

### Adding the output layer

## Part 3 - Training the ANN

### Compiling the ANN

In [149]:
ann.compile(
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01)
)

### Training the ANN on the Training set

In [150]:
ann.fit(X_train,y_train,epochs=40)

Epoch 1/40


/usr/local/lib/python3.11/dist-packages/keras/src/backend/tensorflow/nn.py:780: UserWarning: "`binary_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Sigmoid activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.5256
Epoch 2/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.3674
Epoch 3/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3515
Epoch 4/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3580
Epoch 5/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3632
Epoch 6/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3649
Epoch 7/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3525
Epoch 8/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3421
Epoch 9/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3529
Epoch 10/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3426
Epoch 11/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3460
Epoch 12/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.3609
Epoch 13/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3437
Epoch 14/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3503
Epoch 15/40
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3385


## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Extra**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [151]:
[[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]

[[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]

### Predicting the Test set results

In [152]:
y_pred = ann.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [153]:
y_pred=y_pred.round()

### Making the Confusion Matrix

In [154]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.863
[[1509   76]
 [ 198  217]]


write down about precision recall f1-score, why is it better than just accuracy, what are some other interesting metrics u can find